In [1]:
import numpy as np
y_pred = np.zeros(10000)
y_test = np.zeros(10000)
indices1 = np.random.randint(0,10000,300)
indices2 = np.random.randint(0,10000,400)
indices3 = np.random.randint(0,10000,500)
y_pred[indices1] = 1
y_test[indices2] = 1
y_pred[indices3] = 1
y_test[indices3] = 1

In [2]:
np.sum(y_test)

874.0

In [3]:
np.sum(y_pred)

777.0

In [4]:
from sklearn.metrics import accuracy_score
print('Accuracy score: ',accuracy_score(y_test,y_pred))

Accuracy score:  0.9347


In [8]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[8848,  278],
       [ 375,  499]], dtype=int64)

In [9]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.96      0.97      0.96      9126
         1.0       0.64      0.57      0.60       874

    accuracy                           0.93     10000
   macro avg       0.80      0.77      0.78     10000
weighted avg       0.93      0.93      0.93     10000



In [10]:
from sklearn.metrics import precision_recall_curve
precision, recall, thresholds = precision_recall_curve(y_test,y_pred)

In [11]:
precision

array([0.0874    , 0.64221364, 1.        ])

In [12]:
recall

array([1.        , 0.57093822, 0.        ])

In [13]:
thresholds

array([0., 1.])